config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trees, only: [:show, :index] do
    resources :bookings, only: [:create]
  end

  # resources :bookings, only: [:dashboard]
  get "/dashboard", to: "bookings#dashboard"

  namespace :owner do
    resources :trees, only: [:new, :create, :edit, :update, :destroy]
    # resource :dashboard, only: [:dashboard]
    resources :bookings do
      member do
        patch :decline, :accept
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  # has_one :user, through: :tree
  belongs_to :tree

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
  validates :status, presence: true
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :description, presence: true
  validates :price, presence: true
  validates :species, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :countryname, presence: true
  after_validation :geocode_address, if: [:will_save_change_to_street?, :will_save_change_to_city?, :will_save_change_to_countryname?]
  geocoded_by :geocode_address

  def geocode_address
    full_address = [street, city, countryname].join(", ")

    results = Geocoder.search(full_address)
    lat_long = results.first.coordinates unless results.empty?

    if lat_long && !lat_long.empty?
      self.latitude = lat_long[0]
      self.longitude = lat_long[1]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_one_attached :photo
  # has_many :trees

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def dashboard
    @owner_created_bookings = Booking.includes(:tree).where.not(user: current_user).where(status: "created", tree: { user: current_user })
    @renter_created_bookings = Booking.includes(:tree).where.not(tree: { user: current_user }).where(status: "created", user: current_user)
    @renter_validated_future_bookings = Booking.includes(:tree).where.not(tree: { user: current_user }).where(status: "validated", user: current_user).where('start_date > ?', DateTime.now)
    @renter_validated_past_bookings = Booking.includes(:tree).where.not(tree: { user: current_user }).where(status: "validated", user: current_user).where('end_date < ?', DateTime.now)
    @renter_declined_future_bookings = Booking.includes(:tree).where.not(tree: { user: current_user }).where(status: "declined", user: current_user).where('start_date > ?', DateTime.now)
  end

  def create
    @booking = Booking.new(booking_params)
    @tree = Tree.find(params[:tree_id])
    
    if current_user.nil?
      return redirect_to new_user_session_path, notice: "Please, log yourself first"
    end
    if @booking.end_date.nil? || @booking.start_date.nil?
      return redirect_to tree_path(@tree), notice: "Dates are incorrect"
    end

    @tree = Tree.find(params[:tree_id])
    @booking.tree = @tree
    @booking.user = current_user
    @booking.total_price = @tree.price * (@booking.end_date - @booking.start_date)
    @booking.status = "created"

    if @booking.save

      redirect_to dashboard_path
    else
      render "trees/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :comment)
  end
end

app/controllers/owner/bookings_controller.rb
module Owner
  class BookingsController < ApplicationController

    def decline
      @booking = Booking.find(params[:id])
      @booking.status = "declined"
      @booking.save
      redirect_to dashboard_path
    end

    def accept
      @booking = Booking.find(params[:id])
      @booking.status = "validated"
      @booking.save
      redirect_to dashboard_path
    end


  end
end

app/controllers/owner/trees_controller.rb
module Owner
  class TreesController < ApplicationController
    def new
      @tree = Tree.new
    end

    def create
      @tree = Tree.new(tree_params)
      @tree.user = current_user
      if @tree.save
        redirect_to tree_path(@tree)
      else
        render :new
      end
    end

    private

    def tree_params
      params.require(:tree).permit(:species, :price, :street, :city, :countryname, :description, :photo)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @trees 
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  def show
    @tree = Tree.find(params[:id])
    @user = @tree.user
    @booking = Booking.new
  end

  def index
    @trees = Tree.all
    @markers = @trees.geocoded.map do |tree|
      {
        lat: tree.latitude,
        lng: tree.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tree: tree }),
        image_url: helpers.asset_url("baobabmap.png")
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/dashboard.html.erb
<div class="share">
  <%= link_to "Share your baobab", new_owner_tree_path, class:"btn-flat"%>
</div>
<div class="container dashboard-big-container p-2 mt-5">

  <h1>⏰✔️❔ My own leasings waiting for validation</h1>
  <% if  @owner_created_bookings.exists? %>
    <div class="accordion" id="accordionExample1">
      <%  @owner_created_bookings.each_with_index do |booking, index| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading1<%= index.to_s %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1<%= index.to_s %>" aria-expanded="false" aria-controls="collapse1<%= index.to_s %>">
              My baobab : <%= booking.tree.species %>  ||  Start : <%= booking.start_date %>  ||  End : <%= booking.end_date %>
            </button>
          </h2>
          <div id="collapse1<%= index.to_s %>" class="accordion-collapse collapse" aria-labelledby="heading1<%= index.to_s %>" data-bs-parent="#accordionExample1">
            <div class="accordion-body flex-accordion">
              <%= cl_image_tag(booking.tree.photo.key, width: 200, height: 200, crop: :fill) %>
              <div class="margin-dashboard">
                <%= cl_image_tag(booking.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %>
                <p><%= booking.user.first_name.capitalize %> is waiting for you to review the booking.</p>
              </div>
              <%= link_to "Accept", accept_owner_booking_path(booking.id), method: "patch", class: "btn btn-success btn-dashboard margin-dashboard" %>
              <%= link_to "Reject", decline_owner_booking_path(booking.id), method: "patch", class: "btn btn-danger btn-dashboard margin-dashboard" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>You have no leasing demands waiting for validation</h3>
  <% end %>
</div>

<div class="container dashboard-big-container p-2 mt-5">
  <h1>⏳🌴 My bookings waiting for validation</h1>
  <% if @renter_created_bookings.exists? %>
    <div class="accordion" id="accordionExample2">
      <% @renter_created_bookings.each_with_index do |booking, index| %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="heading2<%= index.to_s %>">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2<%= index.to_s %>" aria-expanded="false" aria-controls="collapse2<%= index.to_s %>">
                Baobab I want to book : <%= booking.tree.species %> | Start : <%= booking.start_date %> | End : <%= booking.end_date %>
              </button>
            </h2>
            <div id="collapse2<%= index.to_s %>" class="accordion-collapse collapse" aria-labelledby="heading2<%= index.to_s %>" data-bs-parent="#accordionExample2">
              <div class="accordion-body flex-accordion">
                <%= cl_image_tag(booking.tree.photo.key, width: 200, height: 200, crop: :fill) %>
                <div class="margin-dashboard">
                  <%= cl_image_tag(booking.tree.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %>
                  <p><%= booking.tree.user.first_name.capitalize %> is still reviewing your booking.</p>
                  <p>It will move to your future bookings section below once accepted.</p>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <% else %>
    <h3>You have no demands waiting for validation</h3>
  <% end %>
</div>

<div class="container dashboard-big-container p-2 mt-5">
  <h1>🌞🌴 My future baobab bookings!</h1>
  <% if @renter_validated_future_bookings.exists? %>
    <div class="accordion" id="accordionExample3">
      <% @renter_validated_future_bookings.each_with_index do |booking, index| %>
        <%# <% if booking.start_date > Date.today && booking.status == "validated" && current_user == booking.user %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading3<%= index.to_s %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse3<%= index.to_s %>" aria-expanded="false" aria-controls="collapse3<%= index.to_s %>">
              The booked baobab  : <%= booking.tree.species %> | Start : <%= booking.start_date %> | End : <%= booking.end_date %>
            </button>
          </h2>
          <div id="collapse3<%= index.to_s %>" class="accordion-collapse collapse" aria-labelledby="heading3<%= index.to_s %>" data-bs-parent="#accordionExample3">
            <div class="accordion-body flex-accordion">
              <%= cl_image_tag(booking.tree.photo.key, width: 200, height: 200, crop: :fill) %>
              <div class="margin-dashboard">
                <%= cl_image_tag(booking.tree.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %>
                <p>You are currently enjoying <%= booking.tree.user.first_name.capitalize %> baobab!</p>
              <p>🌞</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>You have no future baobab bookings awaiting. Start to book boabab for yourself today!</h3>
  <% end %>
</div>

<div class="container dashboard-big-container p-2 mt-5">
  <h1>📜🌴 My past bookings</h1>
  <% if @renter_validated_past_bookings.exists? %>
    <div class="accordion" id="accordionExample4">
      <% @renter_validated_past_bookings.each_with_index do |booking, index| %>
      <%# <% if booking.end_date < Date.today && booking.status == "validated" && current_user == booking.user %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading4<%= index.to_s %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse4<%= index.to_s %>" aria-expanded="false" aria-controls="collapse4<%= index.to_s %>">
              My past baobabs : <%= booking.tree.species %> | Start : <%= booking.start_date %> | End : <%= booking.end_date %>
            </button>
          </h2>
          <div id="collapse4<%= index.to_s %>" class="accordion-collapse collapse" aria-labelledby="heading4<%= index.to_s %>" data-bs-parent="#accordionExample4">
            <div class="accordion-body flex-accordion">
              <%= cl_image_tag(booking.tree.photo.key, width: 200, height: 200, crop: :fill) %>
              <div class="margin-dashboard">
                <%= cl_image_tag(booking.tree.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %>
                <p>How was <%= booking.tree.user.first_name.capitalize %> baobab?</p>
                <p>Leave a boa-review!</p>
              </div>
              <%= link_to "Review", "#", class: "btn btn-primary btn-dashboard margin-dashboard" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>You have no past baobab bookings.</h3>
  <% end %>
</div>

<div class="container dashboard-big-container p-2 mt-5">
  <h1>❌🌴 My declined baobab bookings</h1>
  <% if @renter_declined_future_bookings.exists? %>
    <div class="accordion" id="accordionExample5">
      <% @renter_declined_future_bookings.each_with_index do |booking, index| %>
        <%# <% if booking.start_date > Date.today && booking.status == "validated" && current_user == booking.user %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading5<%= index.to_s %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse5<%= index.to_s %>" aria-expanded="false" aria-controls="collapse5<%= index.to_s %>">
              Declined baobabs : <%= booking.tree.species %> | Start : <%= booking.start_date %> | End : <%= booking.end_date %>
            </button>
          </h2>
          <div id="collapse5<%= index.to_s %>" class="accordion-collapse collapse" aria-labelledby="heading5<%= index.to_s %>" data-bs-parent="#accordionExample5">
            <div class="accordion-body flex-accordion">
              <%= cl_image_tag(booking.tree.photo.key, width: 200, height: 200, crop: :fill) %>
              <div class="margin-dashboard">
                <%= cl_image_tag(booking.tree.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %>
                <p><%= booking.tree.user.first_name.capitalize %> has rejected your booking...</p>
                <p>Book another baoabab today!</p>
              </div>
              <%= link_to "Book", trees_path, class: "btn btn-success btn-dashboard margin-dashboard" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>You had some booking requests declined in the past.</h3>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="links">
    <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-fw fa-github"></i></a>
    <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
    <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
    <p>Part of the Baobab international corporation</p>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
        <br>
        <br>
        <br>
      <%= image_tag "Air baobab-n-baobab.png" %>
    <% end %>



    </button>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "BAOboard", dashboard_path, class: "nav-link mt-5" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link mt-5"%>
          </li>
          <li class="nav-item active">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle mt-5", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
        <% else %>


            <%= link_to "Login", new_user_session_path, class: "nav-link mt-5" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🌴BAOnb🌴</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>

  </head>

  <body>

    <%= render "layouts/nav_bar"%>

    <%= yield %>
    <%= render "layouts/footer"%>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/search.html.erb
<!-- Search -->
		<div class="hero_single jarallax">
		   <div class="wrapper" style="background-color: rgba(0, 0, 0, 0.5);">
				<div class="container">

					<form>
						<div class="row no-gutters custom-find-input-2">
							<div class="col-lg-4">
								<div class="form-group">
									<input class="form-control" type="text" placeholder="Adress...">
									<i class="icon_pin_alt"></i>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<input class="form-control" type="text" name="dates" placeholder="When...">
									<i class="icon_calendar"></i>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="panel-dropdown">
										<!-- Quantity Buttons -->
										<div class="qtyButtons">
											<label>Qty</label>
											<input type="text" name="qtyInput" value="1">
										</div>

										</div>
									</div>
								</div>
							</div>
							<div class="col-lg-2">
								<input type="submit" class="btn_find" value="Find">
							</div>
						</div>
						<!-- /row -->
					</form>
				</div>
			</div>
		</div>
		<!-- /Search -->

app/views/owner/trees/new.html.erb
<div class="container">
  <div class="share-title">
    <h1><strong>Share your baobab</strong></h1>
  </div>
  <div class="form">
    <%= simple_form_for [@tree], url: owner_trees_path do |f| %>
      <%= f.input :species %>
      <%= f.input :street %>
      <%= f.input :countryname, :label => "Country" %>
      <%= f.input :city %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Share", class: "btn-flat" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner banner-container">
  <%= video_tag "video.mp4", autoplay: true, loop: :loop, muted: :muted, id:"myVideo", class: "banner-video" %>
  <div class="container container-hompage-margin">
    <br>
    <br>
    <br>
    <br>
    <h1>Find the Baobab <strong>of your dreams</strong> today </strong>!</h1>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <%= link_to "Find the perfect Baobab", trees_path, class: "btn btn-flat" %>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<h2>Why to rent  a Baobaob?  </h2>
<br>
<div class="cards">
  <a href="https://pedalesetguidon.herokuapp.com/">
    <div class="card-product">
        <img src="https://images.unsplash.com/uploads/14122621859313b34d52b/37e28531" />
        <div class="card-product-infos">
          <h2>We deliver your tree</h2>
          <p> You can create a different look for the space every month, by getting your current tree replaced as often as you like. With this, you can also realise which type of trees look will in environment.
          </p>
          <div>
            <img src="https://pedalesetguidon.herokuapp.com/assets/bicycle-c10bc78e54d1d46f686cfafd94b5275eccbcef7179d73c26dfe0c2f692d76466.png" />
          </div>
      </div>
    </div>
  </a>

  <a href="https://treent.herokuapp.com">
    <div class="card-product">
        <img src="https://images.unsplash.com/photo-1500999753436-5de4f76353f5" />
        <div class="card-product-infos">
          <h2>It is more economical</h2>
          <p> Renting a tree would mean getting more economical ang regular maintenance for your tree. If you are interested in Baobab with fabulous plants we can provide that service thanks or partnership with Treent
          </p>
          <%= image_tag "Treentlogo.png" %>
        </div>
    </div>
  </a>

  <a href="">
    <div class="card-product">
      <img src="https://images.unsplash.com/photo-1504598578017-40d9b776f1bc" />
      <div class="card-product-infos">
        <h2>You change the world</h2>
        <p>We set up programmes for the preservation of natural ecosystems: <br> <br>
            ~ In Indonesia, the focus is on traditional food products.<br>
            ~ In Cameroon, Planète Urgence supports producers to save the dying trees </p>
      </div>
    </div>
  </a>

</div>
<br>
<br>
<br>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1502082553048-f009c37129b9)">
  <div>
						<h1> Are you a <strong>Baobaob owner</strong> ?  Join our network and make money </h1>
            <%= link_to "Rent  your Baobaob", dashboard_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_tree_card.html.erb
<div class="card card_index d-inline-block mt-2" >
          <%= cl_image_tag(tree.photo.key, width: 300, height: 200, crop: :fill) %>
          <div class="card-body">
            <b><p class="card-title"><%= tree.species.capitalize[0..28] %></p></b>
            <p class="card-text"><%= tree.description.capitalize[0..28] %></p>
            <p>€<%= tree.price %></p>
          </div>
        </div>

app/views/trees/_info_window.html.erb
<div class="pop_up">
  <%= cl_image_tag(tree.photo.key, width: 140, height: 140, crop: :fill) %>
  <p><strong><%= "#{tree.species.capitalize} "%></strong> <br> <%= "#{tree.street}, #{tree.city}, #{tree.countryname}" %></p>
  <%= link_to "See more", tree_path(tree.id), class: "btn-flat"%>
</div>

app/views/trees/_search.html.erb
<div class="container d-flex flex-row mr-2 col-sm-3 ">
  <%= form_tag trees_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-search",
      placeholder: "Find a countryname" %>

    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>












<!-- Search -->
		<%# <div class="hero_single jarallax">
		   <div class="wrapper" style="background-color: rgba(0, 0, 0, 0.5);">
				<div class="container">

					<form>
						<div class="row no-gutters custom-find-input-2">
							<div class="col-lg-4">
								<div class="form-group">
									<input class="form-control" type="text" placeholder="Adress...">
									<i class="icon_pin_alt"></i>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<input class="form-control" type="text" name="dates" placeholder="When...">
									<i class="icon_calendar"></i>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="panel-dropdown">
										<!-- Quantity Buttons -->
										<div class="qtyButtons">
											<label>Qty</label>
											<input type="text" name="qtyInput" value="1">
										</div>

										</div>
									</div>
								</div>
							</div>
							<div class="col-lg-2">
								<input type="submit" class="btn_find" value="Find">
							</div>
						</div>
						<!-- /row -->
					</form>
				</div>
			</div>
		</div>
		<!-- /Search --> %>

app/views/trees/index.html.erb
<div class="list_baobab">
  <div class="title">
    <h1><strong>Baobarium </strong><span>🌴<%= @trees.length%> fancy baobabs 🌴</span></h1>
    <%# <%= render "trees/search"%> 
  </div>

  <div class="page_baobab">
    <div class="cards">
      <% @trees.each do |tree| %>
        <%= link_to tree_path(tree), :class => 'link-decoration' do %>
          <div class="card card_index d-inline-block mt-2" >
            <%= cl_image_tag(tree.photo.key, width: 280, height: 200, crop: :fill) %>
            <div class="card-body">
              <p class="card-title"><strong><%= tree.species.capitalize[0..28] %></strong></p>
              <p class="card-text"><%= tree.description.capitalize[0..28] %></p>
              <div class="price">
                <p>€<%= tree.price %></p>
              </div>
            </div>
          </div>
        <% end %>

      <% end %>
    </div>
    <div class="map" style="width: 100%;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/trees/show.html.erb
<div class="baobab_page">
  <div class="navigation">
    <p> < <%= link_to "Back", trees_path %><p>
  </div>
  <div class="baobab_container d-flex justify-content-around">
    <div class="description_baobab">
      <h1><%= "#{@tree.species.capitalize}🌴" %></h1>
      <div class="baobab_image">
        <% if @tree.photo.attached?%>
          <%= cl_image_tag(@tree.photo.key, crop: :fill) %>
        <% end %>
      </div>
      <div class="description">
        <p><%= "#{@tree.description}" %></p>
        <p><i class="fas fa-map-marker-alt"></i> <%= " #{@tree.street}, #{@tree.city}, #{@tree.countryname}" %></p>
        <p><%= cl_image_tag(@tree.user.photo.key, width: 50, height: 45, class: "avatar dropdown-toggle", crop: :fill) %> Contact <%= @tree.user.first_name.capitalize %> </p>
      </div>
    </div>
    <div class="booking_baobab">
      <span><i class="fas fa-euro-sign"></i> <%= "#{@tree.price} / day"%></span>
      <%= simple_form_for [ @tree, @booking ] do |f| %>
        <p>Start date*</p>
        <%= f.date_field :start_date, as: :string,
          data: {
            # controller: "flatpickr",
            # flatpickr_date_format: "d-m-Y",
            # flatpickr_min_date: Time.zone.now
          }, class:"form-control text optional" %>
        <p>End date*</p>
        <%= f.date_field :end_date,
          data: {
            # controller: "flatpickr",
            # flatpickr_date_format: "d-m-Y",
            # flatpickr_min_date: Time.zone.now
          }, class:"form-control text optional" %>
        <%= f.input :comment %>
        <%= f.submit "Book now", class: "btn btn-flat" %>
      <% end %>
    </div>
  </div>
<div>